Repository FNNDSC/ChRIS_store_ui, pull requests merged in 2018-07, with the labels that each got.

#8 Replace sample data with data from the ChRIS store API
  .env
  README.md
  package.json
  src/components/App/App.js
  src/components/Navbar/Navbar.css
  src/components/Navbar/Navbar.js
  src/components/Navbar/Navbar.test.js
  src/components/Navbar/__snapshots__/Navbar.test.js.snap
  src/components/Navbar/components/Search/Search.css
  src/components/Navbar/components/Search/Search.js
  src/components/Navbar/components/Search/Search.test.js
  src/components/Navbar/components/Search/__snapshots__/Search.test.js.snap
  src/components/Plugin/Plugin.js
  src/components/Plugin/Plugin.test.js
  src/components/Plugins/Plugins.js
  src/components/Plugins/Plugins.test.js
  src/components/Plugins/formatPluginList.js
  src/components/Plugins/formatPluginList.test.js
  src/components/Plugins/samplePluginsData.js
  src/components/Router/Router.js
  src/components/Router/Router.test.js
  src/components/Router/__snapshots__/Router.test.js.snap
  src/components/__mocks__/chrisstoreapi.js
  yarn.lock
Labels: needs review

#9 Higher-res and pixel grid-aligned versions of the ChRIS plugin store logo
  src/assets/img/chris-plugin-store_logo.png
  src/assets/img/chris_logo-white.png
  src/components/Footer/Footer.css
  src/components/Footer/Footer.js
  src/components/Footer/Footer.test.js
  src/components/Footer/__snapshots__/Footer.test.js.snap
  src/components/Navbar/Navbar.css
  src/components/Navbar/Navbar.js
  src/components/Navbar/Navbar.test.js
  src/components/Navbar/__snapshots__/Navbar.test.js.snap
Labels: enhancement

#11 Added polyfill and adjusted CSS
  package.json
  src/components/App/App.css
  src/components/Developers/components/BashLine/BashLine.css
  src/components/Developers/components/CopyToClipboard/CopyToClipboard.css
  src/components/Developers/components/DeveloperCTA/DeveloperCTA.css
  src/components/Developers/components/Instructions/Instructions.css
  src/components/Footer/Footer.css
  src/components/Navbar/Navbar.css
  src/components/Plugin/Plugin.css
  src/components/Plugin/components/PluginBody/PluginBody.css
  src/components/Plugins/Plugins.css
  src/components/Plugins/components/PluginItem/PluginItem.css
  src/components/Plugins/components/PluginsCategories/PluginsCategories.css
  src/components/Welcome/components/WelcomeCTA/WelcomeCTA.css
  src/components/Welcome/components/WelcomeCategories/welcomeCategories.css
  src/components/Welcome/components/WelcomeCategory/WelcomeCategory.css
  src/components/Welcome/components/WelcomeChRIS/WelcomeChRIS.css
  src/components/Welcome/components/WelcomeFeature/WelcomeFeature.css
  src/index.js
  yarn.lock
Labels: optimization
